name: Ping URL every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call URL
        run: curl -s https://task-tracker-yuac.onrender.com/
